//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 问卷调查.QHtmlWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QHtmlWebService.QHtmlWebServiceSoap")]
    public interface QHtmlWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Chtml", ReplyAction="*")]
        问卷调查.QHtmlWebService.ChtmlResponse Chtml(问卷调查.QHtmlWebService.ChtmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Chtml", ReplyAction="*")]
        System.Threading.Tasks.Task<问卷调查.QHtmlWebService.ChtmlResponse> ChtmlAsync(问卷调查.QHtmlWebService.ChtmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChtmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Chtml", Namespace="http://tempuri.org/", Order=0)]
        public 问卷调查.QHtmlWebService.ChtmlRequestBody Body;
        
        public ChtmlRequest() {
        }
        
        public ChtmlRequest(问卷调查.QHtmlWebService.ChtmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChtmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Q;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UID;
        
        public ChtmlRequestBody() {
        }
        
        public ChtmlRequestBody(string Q, int UID) {
            this.Q = Q;
            this.UID = UID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChtmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChtmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public 问卷调查.QHtmlWebService.ChtmlResponseBody Body;
        
        public ChtmlResponse() {
        }
        
        public ChtmlResponse(问卷调查.QHtmlWebService.ChtmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChtmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChtmlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string url;
        
        public ChtmlResponseBody() {
        }
        
        public ChtmlResponseBody(string ChtmlResult, string url) {
            this.ChtmlResult = ChtmlResult;
            this.url = url;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QHtmlWebServiceSoapChannel : 问卷调查.QHtmlWebService.QHtmlWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QHtmlWebServiceSoapClient : System.ServiceModel.ClientBase<问卷调查.QHtmlWebService.QHtmlWebServiceSoap>, 问卷调查.QHtmlWebService.QHtmlWebServiceSoap {
        
        public QHtmlWebServiceSoapClient() {
        }
        
        public QHtmlWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QHtmlWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QHtmlWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QHtmlWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        问卷调查.QHtmlWebService.ChtmlResponse 问卷调查.QHtmlWebService.QHtmlWebServiceSoap.Chtml(问卷调查.QHtmlWebService.ChtmlRequest request) {
            return base.Channel.Chtml(request);
        }
        
        public string Chtml(string Q, int UID, out string url) {
            问卷调查.QHtmlWebService.ChtmlRequest inValue = new 问卷调查.QHtmlWebService.ChtmlRequest();
            inValue.Body = new 问卷调查.QHtmlWebService.ChtmlRequestBody();
            inValue.Body.Q = Q;
            inValue.Body.UID = UID;
            问卷调查.QHtmlWebService.ChtmlResponse retVal = ((问卷调查.QHtmlWebService.QHtmlWebServiceSoap)(this)).Chtml(inValue);
            url = retVal.Body.url;
            return retVal.Body.ChtmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<问卷调查.QHtmlWebService.ChtmlResponse> 问卷调查.QHtmlWebService.QHtmlWebServiceSoap.ChtmlAsync(问卷调查.QHtmlWebService.ChtmlRequest request) {
            return base.Channel.ChtmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<问卷调查.QHtmlWebService.ChtmlResponse> ChtmlAsync(string Q, int UID) {
            问卷调查.QHtmlWebService.ChtmlRequest inValue = new 问卷调查.QHtmlWebService.ChtmlRequest();
            inValue.Body = new 问卷调查.QHtmlWebService.ChtmlRequestBody();
            inValue.Body.Q = Q;
            inValue.Body.UID = UID;
            return ((问卷调查.QHtmlWebService.QHtmlWebServiceSoap)(this)).ChtmlAsync(inValue);
        }
    }
}
