//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 问卷调查
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuInfo
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Portrait { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoleTypeID { get; set; }
        public Nullable<int> leven { get; set; }
    }
}
