//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 问卷调查
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int PaperType { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> PaperCount { get; set; }
    }
}
