//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 问卷调查
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireDetailInfo
    {
        public int ID { get; set; }
        public int PaperType { get; set; }
        public int probType { get; set; }
        public int State { get; set; }
        public int QuestionnaireInfoId { get; set; }
        public string Content { get; set; }
        public string Answer { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string OptionE { get; set; }
        public string OptionF { get; set; }
        public int number { get; set; }
    }
}
