//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 问卷调查
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string Id_Guid { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public int type { get; set; }
        public Nullable<int> RoleID { get; set; }
    }
}
